spring:
  application:
    name: inventory-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:inventory_db}
    username: ${DB_USER:orderflow}
    password: ${DB_PASSWORD:orderflow}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false

  flyway:
    enabled: true
    locations: classpath:db/migration

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: inventory-service
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: '*'
        spring.json.add.type.headers: false
    producer:
      properties:
        spring.json.add.type.headers: false

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

orderflow:
  jwt:
    secret: ${JWT_SECRET:ZmFrZS1kZXYtc2VjcmV0LWtleS1jaGFuZ2UtbWUtaW4tcHJvZHVjdGlvbi0xMjM0NTY=}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
